"""empty message

Revision ID: 03beec3e84cb
Revises: 3b5e9a1e5259
Create Date: 2023-08-19 18:57:03.043677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03beec3e84cb'
down_revision = '3b5e9a1e5259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['image_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
