"""empty message

Revision ID: 29df77736b28
Revises: bfaeee3b6555
Create Date: 2023-09-19 11:55:14.702382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29df77736b28'
down_revision = 'bfaeee3b6555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_item', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
