"""empty message

Revision ID: bfaeee3b6555
Revises: e69b34e89b76
Create Date: 2023-09-19 11:47:58.335822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaeee3b6555'
down_revision = 'e69b34e89b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('quote_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['quote_item_id'], ['quote_item.id'], ),
    sa.PrimaryKeyConstraint('quote_id', 'quote_item_id')
    )
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='products_product_id_fkey'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name='products_quote_id_fkey'),
    sa.PrimaryKeyConstraint('quote_id', 'product_id', name='products_pkey')
    )
    op.drop_table('quote_items')
    op.drop_table('quote_item')
    # ### end Alembic commands ###
